APP:
  name: exchange   #服务名称
  ip: 127.0.0.1
  port: 8080
  mode: run   #运行模式
  webIndex: "../initialize/dist"      # web html目录
  filePath: "cloud"  #文件存放目录
  staticFS: false  #是否开静态资源访问


MySQL:
  driverName: mysql
  host: 106.12.19.43
  port: 6446
  database: web_bucked
  username: root
  password: root
  charset: utf8mb4

Redis:
  addr: 120.46.48.255
  port: 6379
  password:
  db: 0
  poolSize: 10
  minIdleConns: 5